<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
  'AvaCms\Module'                            => __DIR__ . '/Module.php',
  'AvaCms\Mvc\Controller\AbstractController' => __DIR__ . '/src/AvaCms/Mvc/Controller/AbstractController.php',
);
